DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  post TEXT NOT NULL,
  visible INTEGER DEFAULT 0 NOT NULL,
  post_position INTEGER DEFAULT 0 NOT NULL,
  menu_name TEXT UNIQUE,
  menu_position INTEGER DEFAULT 0 NOT NULL,
  menu_visibility INTEGER DEFAULT 0 NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);


INSERT INTO user (`username`, `password`) VALUES('asif.testbox@gmail.com', 'pbkdf2:sha256:260000$5qW2WFHUEAB7Q67j$ef1429c2f2f26318704e2918b1f2ae74f5bd62bfd72f55967dc3dda185f31005');

